version: '3.8'
services:
  lint-check:
    image: cypress-cucumber-lint
    build:
      context: ../
      dockerfile: .ci/Dockerfile.lint
    container_name: cypress-lint
    command: format:check:all
