version: '3.8'
services:
  cypress-sanity:
    image: cypress-cucumber
    build:
      context: ../
      dockerfile: .ci/Dockerfile.tests
    container_name: cypress-sanity
    command: npx cypress run --spec "cypress/e2e/features/sanity/*.feature"
  cypress-e2e:
    image: cypress-cucumber
    build:
      context: ../
      dockerfile: .ci/Dockerfile.tests
    container_name: cypress-e2e
    command: npx cypress run --spec "cypress/e2e/features/e2e/*.feature"
