version: '3.8'
services:
  cypress-smoke:
    image: cypress-cucumber
    build:
      context: ../
      dockerfile: .ci/Dockerfile.tests
    container_name: cypress-smoke
    command: npx cypress run --spec "cypress/e2e/features/smoke/*.feature"
